export const CLIENT_ACCOUNT_MARGIN_ADAPTER = 'CLIENTACCOUNTMARGIN.CLIENTACCOUNTMARGIN';
export const NEWS_ADAPTER = 'NEWS.HEADLINES';
export const ORDER_ADAPTER = 'ORDERS.ORDERS';
export const PRICE_ADAPTER = 'PRICES.PRICE';
export const PRICE_ALERTS_ADAPTER = 'PRICEALERTS.PRICEALERTS';
export const QUOTES_ADAPTER = 'QUOTES.QUOTES';
export const TRADE_MARGIN_ADAPTER = 'TRADEMARGIN.TRADEMARGIN';
